### ISSUE TITLE
OpenAI missuse of '#' in javascript class in webinterface framework

### ISSUE THREAD

**Issue by designerfuzzi** [openai/openai-openapi#101]
Knowing this is not the right place to report, but after hours of digging in OpenAi pages, there is literally no address or place found to report bugs for the webinterface.

The webinterface chat.openai.com was working properly until 24th October 2023 ~23:59, ever since after the login or any access to the website is messed up as one can read below, no access possible.
 
```
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (login, line 1, x2)
[Error] SyntaxError: Unexpected private name #n. Cannot parse class method with private name.
	(anonyme Funktion) (_app-7b25e5d48a5be880.js:11)
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (login, line 0)
```

this bug says that a class uses "#n" as internal class variable but obviously runs into dead end as it can not be accessed from outside the class thus the name scheme with leading '#' forces this behaviour. 

That means that not even the login dialog at https://chat.openai.com/auth/login can appear since two days. Leads to a strange question, does someone test the webinterface before commits are rolled out to all? 

I was able to manage to be logged in but the webinterface still shows the very same bug of course. The framework is messed up since 25th October. Before it just worked, so it is a roll out issue

**Comment by designerfuzzi** [comment]
In other words, Chrome is less strict with executing javascript. Guess what it potentially a security issue...

**Comment by logankilpatrick** [comment]
Hey @designerfuzzi are you still getting this issue? I am going to close this for now but please let me know if you are so I can flag to the team.

**Comment by designerfuzzi** [comment]
still the same. Using Safari > login > then blank page ever after. In comparison same same with Chrome works fine but surprise i found out google catches what i am writing there, which an even bigger issue. So i tend to look forward using Safari again if that can be fixed.
