### ISSUE TITLE
createFile operation has incorrect `file` body type

### ISSUE THREAD

**Issue by transitive-bullshit** [openai/openai-openapi#123]
The [docs](https://platform.openai.com/docs/api-reference/files/create) say `file` should be a `string`.

The openapi spec say that `body.file` should be a [string](https://github.com/openai/openai-openapi/blob/a7a0b63d1fac3acac9a223d57da1219c8a97c01e/openapi.yaml#L6773-L6777) encoded as `binary` (which would be super inefficient, but that's besides the point of this issue).

But the `openai-node` client generates an **object** for `file`, and that's what the OpenAI API backend expects.

Here's an example `file` sent to the `POST /files` endpoint parsed as `multipart/form-data`:

```
File {
  size: 7594,
  type: 'application/octet-stream',
  name: 'readme.md',
  lastModified: 1700076420900
}
```

You can repro this with:

```ts
import fs from 'node:fs'
import OpenAI from 'openai'

  const openai = new OpenAI({
    baseURL: baseUrl
  })

  const readmeFileStream = fs.createReadStream('readme.md', 'utf8')

  const readmeFile = await openai.files.create({
    file: readmeFileStream,
    purpose: 'assistants'
  })
  console.log('created readme file', readmeFile)
```

If you use a custom `baseUrl` and print out the formData sent for this simple example, the `file` property of the request body will be an object, not a string.

**Comment by transitive-bullshit** [comment]
Note: this is also really important because otherwise, the server would have no way of knowing what the filename is, so taking in a `binary`-formatted string makes no sense and would be pretty inefficient.

cc @rattrayalex

**Comment by rattrayalex** [comment]
Thanks Travis! I agree, the docs UI should be fixed to display `type: string, format: binary` as a `file` instead of a `string`.

Note that I don't think `type: string, format: binary` is incorrect based on my read of the docs: https://swagger.io/docs/specification/describing-request-body/file-upload/

**Comment by schnerd** [comment]
Thank you! Alex is right, the OpenAPI spec should be correct and our docs are not handling this case well. We'll deploy the fix to the docs in the next day or two:

<img width="412" alt="Screenshot 2023-11-15 at 7 36 21 PM" src="https://github.com/openai/openai-openapi/assets/875591/4f5c320b-25f2-4c6f-a569-1ad5bc08dc0e">

**Comment by transitive-bullshit** [comment]
Thanks, guys! 🙏 

Yeah, I think the issue I was running into was an edge case in https://github.com/transitive-bullshit/OpenOpenAI where the `multipart/form` body was being parsed with `purpose: string` and `file: File` as opposed to `file: string`. Probably not anything most folks will run into. Appreciate the quick turnaround && thanks again!
