### ISSUE TITLE
Date gives the past date not the actual one

### ISSUE THREAD

**Issue by VirajMadhu** [openai/openai-openapi#13]
I was checking it on 24th January 2023. But AI gives the past date. I'm using openai api in my personal project.

![image](https://user-images.githubusercontent.com/81850588/214204476-fbd5f58b-04a9-4c88-b078-d0c763331948.png)

**Comment by logankilpatrick** [comment]
This repo is for the OpenAPI spec we supply, not general feedback, please head to https://community.openai.com for broader discussions.
