### ISSUE TITLE
typo: `"type":` instead of `"type:`

### ISSUE THREAD

**Issue by mefengl** [openai/openai-openapi#134]
https://github.com/openai/openai-openapi/blob/23a4b18b65bb7b002894bae1084d99134b2897e3/openapi.yaml#L5850

**Comment by 2catycm** [comment]
It seems this has been fixed? 
![image](https://github.com/openai/openai-openapi/assets/41530341/a4c31ec0-b9d8-4ce7-b8a5-feff52a36fbd)
