### ISSUE TITLE
Invalid default engine for edit creation endpoint

### ISSUE THREAD

**Issue by Rabrg** [openai/openai-openapi#2]
The "example request" section of our edit creation endpoint docs defaults to the engine `text-davinci-002`, which is incompatible with the edit endpoint

<img width="489" alt="image" src="https://user-images.githubusercontent.com/654846/159588033-7106f0a9-4daa-4d21-9930-3fef7ee998d7.png">

Quickly looked to see if I could find out how to change this, but was unable to, so creating this issue instead

**Comment by om4james** [comment]
Looking at https://platform.openai.com/docs/api-reference/edits, this appears to have been fixed.


![Screenshot 2023-02-07 at 11 40 52 am](https://user-images.githubusercontent.com/108233/217142719-f241675e-36fb-4ebf-9a81-e899d9a25924.png)

**Comment by logankilpatrick** [comment]
Closing this since I fixed it a while back in the linked thread!
