### ISSUE TITLE
Requesting a sync from the internal OpenAPI spec

### ISSUE THREAD

**Issue by thedadams** [openai/openai-openapi#208]
I know this is relatively fresh, but stream support for runs has been added. It would be great to get this in the public OpenAPI spec.

**Comment by StephenHodgson** [comment]
+1

**Comment by sashirestela** [comment]
A sync would be great, especially for the Assistant API Stream Events, however I was able to implement it for my Java library using the official documentation. If you are curious take a look at:

https://github.com/sashirestela/simple-openai/pull/65/files
