### ISSUE TITLE
RunStatus incomplete missing

### ISSUE THREAD

**Issue by vpzomtrrfrt** [openai/openai-openapi#256]
The documentation for the `status` field on a Run says:
> The status of the run, which can be either `queued`, `in_progress`, `requires_action`, `cancelling`, `cancelled`, `failed`, `completed`, or `expired`.

However, there appears to be another possibility, "incomplete"

**Comment by davidmigloz** [comment]
It's already added in https://github.com/openai/openai-openapi/commit/df5699f5c48fe455d9d036198e77fdb637edee29
