### ISSUE TITLE
`quote` should be nullable in `MessageContentTextAnnotationsFileCitationObject`

### ISSUE THREAD

**Issue by davidmigloz** [openai/openai-openapi#263]
The `quote` property is marked as required, but the server doesn't include them in all the cases.

https://github.com/openai/openai-openapi/blob/893ba52242dbd5387a97b96444ee1c742cfce9bd/openapi.yaml#L11362-L11397

Example of response that doesn't include it:

```json
{
  "id": "msg_Fn6zTxxx",
  "object": "thread.message",
  "created_at": 1715820384,
  "assistant_id": "asst_K4iArkxxx",
  "thread_id": "thread_3N31Erp0eCVhAhKh5BdMk1aQ",
  "run_id": "run_icH57L9xxx",
  "status": "completed",
  "incomplete_details": null,
  "incomplete_at": null,
  "completed_at": 1715820391,
  "role": "assistant",
  "content": [
    {
      "type": "text",
      "text": {
        "value": "...",
        "annotations": [
          {
            "type": "file_citation",
            "text": "【6:0†source】",
            "start_index": 1109,
            "end_index": 1121,
            "file_citation": {
              "file_id": "file-TrXXpxxx"
            }
          }
        ]
      }
    }
  ],
  "attachments": [],
  "metadata": {}
}
```

**Comment by dahifi** [comment]
Jumping in here. We did a fair amount of work in v1 to get this rendering well, and it seems like the quote is no longer returned for any of the v2 endpoints. Some of the older models might still do it, but not the new ones. 

There are a couple threads on the community server, including [this one](https://community.openai.com/t/how-can-i-access-the-specific-text-of-the-file-that-the-annotation-is-referencing/726723/5) with response from OAI staff member that it's not supported but "we'll work on" it. 

Not sure where else to track it, but this OpenAPI repo seems more appropriate than the python API one. 

But yes, I can also imagine that this causes `_strict_response_validation` to fail on every call.

**Comment by nknj** [comment]
Apologies for the oversight here -- we just rolled out a fix to remove `quote` from the openapi spec and will roll out updated sdks shortly.

**Comment by dahifi** [comment]
> Apologies for the oversight here -- we just rolled out a fix to remove `quote` from the openapi spec and will roll out updated sdks shortly.

Not sure if this is the place to discuss this further, but having the quote available at the client level is going to be crucial for RAG validation. Removing it is a bad move.

**Comment by Adham-Mamedov** [comment]
@nknj Is team going to add quotes back? 
It was really helpful in v1. I am working with legal documents, so having direct quotes would decrease the chance of assistant misinterpretation and errors.

**Comment by DennisPeeters** [comment]
Indeed, same issue

**Comment by sheldonrampton** [comment]
The 'quote' attribute is referenced in the OpenAI documentation:

https://platform.openai.com/docs/assistants/deep-dive/managing-threads-and-messages

If it has been removed, the documentation needs to be updated.

**Comment by eirikora** [comment]
In current version, I seem to be experiencing the same issue. See:
https://github.com/openai/openai-python/issues/1498#issuecomment-2345692701
