### ISSUE TITLE
OpenAPI document logit_bias default value

### ISSUE THREAD

**Issue by reactiveclown** [openai/openai-openapi#27]
There is an issue in the documentation. In the section https://platform.openai.com/docs/api-reference/completions/create

It is said, that default value for [logit_bias](https://platform.openai.com/docs/api-reference/completions/create#completions/create-logit_bias) should be null but in reality it is `empty map`
![image](https://user-images.githubusercontent.com/124299308/224333539-b01c5890-9f85-421b-aacc-fe8f042cbe11.png)

If we are passing **null** as the argument, we will receive an exception. But passing empty map works just fine.

Kindly see two screenshots below.

**Empty map as a value**
![image](https://user-images.githubusercontent.com/124299308/224333159-3b560017-463c-41aa-b538-ae43f58ee433.png)

**`null` as a value**
![image](https://user-images.githubusercontent.com/124299308/224333386-25cf17fa-a9a1-4b71-9365-fff499b806c9.png)

**Comment by logankilpatrick** [comment]
Defaults to null in this context means that if you don't pass in null, that is the value we set behind the scenes. It does not mean that null is a valid option to pass in. I am going to close this out but feel free to add other thoughts here.
