### ISSUE TITLE
Mismatching behaviour of fine-tune endpoint compared to its openAPI contract definition

### ISSUE THREAD

**Issue by NipunaRanasinghe** [openai/openai-openapi#29]
We are working on a openAI connector written in Ballerina language, using its openAPI contract.  

During the effort, we've observed that even though the `validation_file, batch_size, learning_rate_multiplier, classification_n_classes, classification_positive_class, classification_betas,  and suffix` properties of the fine tune create request are labeled as nullable (as per the API documentation (https://platform.openai.com/docs/api-reference/fine-tunes/create) and in the openAPI contract), the openAI backend doesn't accept null values for the same and fails with errors such as `None is not of type string`.

What should be the expected behaviour in here? should we remove the `nullable: true` property for the above fields or, should the backend be fixed to accept null values for the above case?

**Comment by logankilpatrick** [comment]
I am going to close this out as the fine-tunes endpoint is being deprecated, please let me know if this is an issue on the new /fine_tuning/jobs endpoint.
