### ISSUE TITLE
"Name" property on ChatCompletionRequestMessage not in API reference

### ISSUE THREAD

**Issue by JustinGrote** [openai/openai-openapi#30]
https://platform.openai.com/docs/api-reference/chat/create

The "name" property is not present on the response message type, only the request message type, and it doesn't seem to do anything and isn't documented. Is it still needed or should it be removed to avoid confusion?

**Comment by conacts** [comment]
The "name" property is needed when you use [chat functions](https://platform.openai.com/docs/guides/gpt/function-calling). Here is an example of the messages parameter in python. Note that you should not explicitly write the function name but have it generated by ChatCompletion as described in [this documentation](https://platform.openai.com/docs/guides/gpt/function-calling):
```json
 {
    "role": "user", 
    "content": user_message, 
    "name": get_current_weather
}
```

Here is an example provided in the [OpenAI Documentation](https://platform.openai.com/docs/guides/gpt/function-calling)
```python
    functions = [
        {
            "name": "get_current_weather",
            "description": "Get the current weather in a given location",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "The city and state, e.g. San Francisco, CA",
                    },
                    "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                },
                "required": ["location"],
            },
        }
    ]
```

Here is the function called by as described by the JSON above:
```python
def get_current_weather(location, unit="fahrenheit"):
    """Get the current weather in a given location"""
    weather_info = {
        "location": location,
        "temperature": "72",
        "unit": unit,
        "forecast": ["sunny", "windy"],
    }
    return json.dumps(weather_info)
```
