### ISSUE TITLE
realtime beta api spec

### ISSUE THREAD

**Issue by StephenHodgson** [openai/openai-openapi#341]
Hi I was wondering when the [reatime api](https://openai.com/index/introducing-the-realtime-api) spec will be added?

I see there are docs but wasn't able to find them in the current spec.

**Comment by benadamdev** [comment]
I don't think that's possible. This spec is primarily designed for HTTP-based RESTful APIs. Realtime API is a WebSocket API not a RESTful one.

**Comment by StephenHodgson** [comment]
@benadamdev there's no reason why it cannot be added. the only real difference is the protocol. Path and payload objects are still defined in json.

I thought [OpenAPI had websocket spec proposal](https://github.com/OAI/OpenAPI-Specification/pull/2881)? ... oh it was never accepted 😕

Well in either case it'd be great to have a machine readable spec for the json objects and paths 🤷

**Comment by StephenHodgson** [comment]
fwiw there [are ways to use fastapi to build out ws paths](https://www.geeksforgeeks.org/documenting-websocket-apis-with-swagger)...

**Comment by benadamdev** [comment]
@StephenHodgson Thank you very much for this. Although this  not a REST API, the schemas section is a real gem from a code generation perspective. Coming from Microsoft, this is pretty official to me. Thanks again.

**Comment by StephenHodgson** [comment]
Regardless if it is not a REST API, I think it is perfectly acceptable to add the schema object definitions to the OpenAPI spec here.

**Comment by StephenHodgson** [comment]
Added in #356
