### ISSUE TITLE
Several component schemas are missing the `type` field

### ISSUE THREAD

**Issue by shonfeder** [openai/openai-openapi#38]
IIUC, all of these should have `type: "object"`:

https://github.com/openai/openai-openapi/blob/master/openapi.yaml#L3434-L3564

For lack of the type field, my tooling is identifying theses schemas as unstructured.

**Comment by logankilpatrick** [comment]
Hey @shonfeder, thanks for flagging, please open a new issue if this is still wrong, I think we have updated the lines you were referring too as they look correct as of now.

**Comment by shonfeder** [comment]
There are still schema missing their types. If you convert the schema to json via yq, you get a report on all the schema with `properties` but no object type via:

```
jq < _build/default/client/openai-spec.json '.components.schemas | to_entries | map(select((.value | has("properties")) and (.value | has("type") | not))) | map(.key)'
[
  "ImagesResponse",
  "Model",
  "OpenAIFile",
  "ListThreadsResponse",
  "ListMessagesResponse",
  "ListRunStepsResponse",
  "ListAssistantFilesResponse",
  "ListMessageFilesResponse"
]
```
