### ISSUE TITLE
Where might one provide feedback?

### ISSUE THREAD

**Issue by morgzz** [openai/openai-openapi#40]
To boot, I realize this is not the best place to submit this type of feedback, I looked through all the typical places, including asking chat.openai.com where might one provide product feedback. But the simplest answer eludes even the AI 😃 .

### AI response
![image](https://user-images.githubusercontent.com/880477/236099695-d42c118d-c0fc-4969-8ac4-d21dd958a192.png)

### Chat menu
![image](https://user-images.githubusercontent.com/880477/236099912-e950a62f-618f-4a19-8aba-5ec68b7633cb.png)

Settings wasn't helpful as well.

### Website footer
![image](https://user-images.githubusercontent.com/880477/236099813-8fbc6b12-a7c3-4340-b1e7-18e2eb720eda.png)

### Safety webpage
![image](https://user-images.githubusercontent.com/880477/236102162-974cf656-2cb8-4332-9baf-e080a9b6d922.png)

### Help Center
![image](https://user-images.githubusercontent.com/880477/236100005-105c8acc-4fc8-4352-bdb2-6316ac76d904.png)

> It was only when I asked the Help Chat Bot, Product Feedback appeared.

![image](https://user-images.githubusercontent.com/880477/236101664-9949aefe-31f9-4a31-a9f8-20e940f2f6e1.png)

Could a link to feedback be included on all the usual places a user might find such link.

> Wanted to provide feedback that would allow pressing up-arrow on the keyboard while input textbox is in current focus which would duplicate/copy the content from previous interaction, but would block submitting duplicate responses to promote unique interactions. 

An appreciative openai user.

**Comment by logankilpatrick** [comment]
Hey! Depends what you want to provide feedback on, this repo is for the OpenAPI spec related to our API, we have SDK repos, a developer forum, forms specific to model feedback, etc. Let me know what you are trying to share and I can point you to the right place.
