### ISSUE TITLE
`usage` information missing for Create Completions, Create Edits and Create Embeddings responses

### ISSUE THREAD

**Issue by om4james** [openai/openai-openapi#5]
In June, `usage` info was [added to several API responses](https://community.openai.com/t/usage-info-in-api-responses/18862).

The API Reference documentation was updated in three places:

- [Create Completions](https://beta.openai.com/docs/api-reference/completions/create)
- [Create Edits](https://beta.openai.com/docs/api-reference/edits/create)
- [Create Embeddings](https://beta.openai.com/docs/api-reference/embeddings/create)

However, this data is missing from the OpenAPI specification.

Can this please be added?

@schnerd do you know if this is likely to be added soon?

Thank you

**Comment by schnerd** [comment]
Just added this – published in openai-node 3.0.1

**Comment by om4james** [comment]
Thank you @schnerd, having `usage` info is great 👏
