### ISSUE TITLE
Is this not being maintained?

### ISSUE THREAD

**Issue by vhpoet** [openai/openai-openapi#6]
Looks like this is not being maintained? Don't see [embeddings](https://beta.openai.com/docs/guides/embeddings/what-are-embeddings) here.

**Comment by om4james** [comment]
Hi @vhpoet, 

I see them here: https://github.com/openai/openai-openapi/blob/45a7d3cc4c6ea83ee8670c8335d4f89be35a9246/openapi.yaml#L492

James

**Comment by kinlane** [comment]
OpenAI folks. If you publish the OpenAPI and collection to a public Postman API workspace under your team account my team (and the community) can help you keep up to date and submit PR requests. You can keep synced here too. Let me know -- happy to help.

**Comment by logankilpatrick** [comment]
Hey @kinlane I will investigate this internally and follow up!

**Comment by kinlane** [comment]
Sounds good @logankilpatrick -- let us know how we can help.

**Comment by arlemi** [comment]
@logankilpatrick FWIW [the parent collection](https://www.postman.com/devrel/workspace/openai/documentation/13183464-90abb798-cb85-43cb-ba3a-ae7941e968da?entity=&branch=&version=) is already on 600+ forks (without any promotion 😅). Happy to walk you through use-cases for public workspaces and show you can automate the collection generation/updates. Feel free to connect directly on arlemi@postman.com if that's easier.

**Comment by logankilpatrick** [comment]
Closing this for now since indeed this repo is being maintained.
