### ISSUE TITLE
List Models API lacks Chat vs Completion field

### ISSUE THREAD

**Issue by tanmayc98** [openai/openai-openapi#61]
The current list models API doesn't not indicate whether a certain model should be called through Completion or ChatCompletion - making it impossible to route requests correctly in production without explicit hardcoded mapping. This should be added as a field to the https://platform.openai.com/docs/api-reference/models/list API.

**Comment by logankilpatrick** [comment]
Agreed, takes some large changes to make this happen but the team agrees!

**Comment by logankilpatrick** [comment]
Closing this out for now but the team is tracking these!

**Comment by supersteves** [comment]
I find it frustrating that this was reported in 2023 and is surely of widespread use, but has been closed and forgotten for so long. 

The (beautiful) new [models](https://platform.openai.com/docs/models) page shows there is a large amount of structured data internally at OpenAI about each model, but the models endpoint only exposes very limited information.

Any third party app therefore has to maintain its own information about OpenAI models. Given new models seem to be released now almost weekly, this is impossible to keep up with. computer-use-preview, gpt-4o-mini-search-preview, for example.

Our 3rd party app lets users (who implicitly are OpenAI customers) pick a model. Why can't we get at all the information that tells us which endpoints models are compatible with, costs per token, intelligence levels, speed, input media etc.? Our app only uses chat completions, but equally we want new chat compatible models to be immediately available, so we are left forced to reveal all new models, including incompatible ones, while we try to  catch up with updating our own metadata.

Please expand the models endpoint to add this information. 🙏
