### ISSUE TITLE
New Fine-Tuning Job API Endpoints missing

### ISSUE THREAD

**Issue by om4james** [openai/openai-openapi#74]
The [new Fine-Tuning Job functionality announced overnight](https://openai.com/blog/gpt-3-5-turbo-fine-tuning-and-api-updates) is not currently included in the OpenAI OpenAPI specification.

Can the new `/fine_tuning/jobs` endpoints and methods please be added to the OpenAPI specification?

Docs:

- https://platform.openai.com/docs/guides/fine-tuning/use-a-fine-tuned-model
- https://platform.openai.com/docs/api-reference/fine-tuning/create

The functionality has been [added to the Python SDK](https://github.com/openai/openai-python/pull/582) and also the [node SDK](https://github.com/openai/openai-node/commit/ddb2815759d027af77ba05bc22c089d8237e008a) but I can't find anywhere where it's been added to the OpenAPI spec.

Thank you

**Comment by logankilpatrick** [comment]
This is fixed via #77, thanks for flagging!
