### ISSUE TITLE
ChatGPT replies in Russian get truncated

### ISSUE THREAD

**Issue by Anixx** [openai/openai-openapi#9]
I do not know if this is related to OpenAPI but could not find a place to file a bug report against ChatGPT. The long replies of ChatGPT in Russian laguage in ChatGPT web interface get truncated at about 1/3 or half of the whole answer. Sometimes this can be worked around by asking ChatGPT to re-post the last answer starting from certain words.

I suspect, this is related to the fact that Cyrillic letters take more bytes in Unicode than Latin letters.

**Comment by logankilpatrick** [comment]
Hey! Please use the built in ChatGPT modal for feedback so it can get to the right place.
