### ISSUE TITLE
`inf` default value cannot be encoded in many languages

### ISSUE THREAD

**Issue by andreaTP** [openai/openai-openapi#93]
Hi there 👋 and thanks a lot for sharing this spec as it immensely helps!

I'm working on [Kiota](https://github.com/microsoft/kiota) and while generating clients for your OpenAPI specification I faced a few issues and reported them, but, in this case, I'm convinced that the specification that can be improved.
[Here](https://github.com/openai/openai-openapi/blob/2c0f330906a93d8492b4dfabd9a38d9cfedcd3eb/openapi.yaml#L2922) you are defining the default value of an `integer` with the string `"inf"` and [here](https://github.com/microsoft/kiota/issues/3398) I reported upstream the bug found.

Still, there is room for improvement:
- `inf` in languages where the `integer` type is translated(according to the spec) as a Long/Int64 an infinite value is not easily representable
- using `inf` as a valid value is only possible in languages that are using `Double`, `BigInt` or similar encodings for all of the numeric values
- `inf` is effectively a `string` here and its meaning can vary across different target languages (I'm failing to find a spec that defines this specific string as a valid `integer` value)

I think that a sensible default would be the value of `32768` since, according to [the docs](https://platform.openai.com/docs/models/continuous-model-upgrades), is currently the maximum number of tokens for the biggest available model.
I'm happy to open a PR if this is the desired resolution of the issue 🙂

**Comment by andreaTP** [comment]
Just figured out that, depending on the resolution of #28 another alternative is to simply remove the `default` field.

**Comment by logankilpatrick** [comment]
Agreed, will remove the default field in an upcoming PR, thank you for flagging!

**Comment by andreaTP** [comment]
That's fine as well!
Thanks for getting back.

**Comment by andreaTP** [comment]
This has been solved on current `main`:
https://github.com/openai/openai-openapi/blob/9d36a3338ec69e9e449f86a988fef0627d49fb52/openapi.yaml#L5933
