### ISSUE TITLE
Model schema object is not complete

### ISSUE THREAD

**Issue by imitko** [openai/openai-openapi#98]
The response from /models returns following (excerpt):
```
		{
			"id": "gpt-4-0314",
			"object": "model",
			"created": 1687882410,
			"owned_by": "openai",
			"permission": [
				{
                                    ...
				}
			],
			"root": "gpt-4-0314",
			"parent": null
		},
```
The schema only contains id, object, created and owned_by. The rest may be intentionally not listed in the schema part of the openapi.yaml document, but I've found "root" & "parent" to be quite useful for knowing which model a fine-tuned one was created from.

**Comment by logankilpatrick** [comment]
Where do you see the root and parent responses? I don't get those when I send a request to retrieve or list models.
